import img from "../assets/images/loe.jpg"

export const contacts = [
    { id: 1, name: 'John Doe', phoneNumber: '+2347012345678', status: 'Online', avatar: null},
    { id: 2, name: 'Jane Smith', phoneNumber: '+2347023456789', status: 'Offline', avatar: img },
    { id: 3, name: 'Michael Johnson', phoneNumber: '+2347034567890', status: 'Online', avatar: null },
    { id: 4, name: 'Mary Johnson', phoneNumber: '+2347045678901', status: 'Busy', avatar: null },
    { id: 5, name: 'Chris Evans', phoneNumber: '+2347056789012', status: 'Offline', avatar: null },
    { id: 6, name: 'Joe Nnamdi', phoneNumber: '+2347043952140', status: 'Offline', avatar: null },
    { id: 7, name: 'Christian Elvis', phoneNumber: '+2347056789012', status: 'Offline', avatar: null },
    { id: 8, name: 'Chris Chukwu', phoneNumber: '+2347054789012', status: 'Offline', avatar: null },
    { id: 9, name: 'Chris Evans', phoneNumber: '+2347020789012', status: 'Offline', avatar: null },
    { id: 10, name: 'Naruto Uzumaki', phoneNumber: '+2347056789112', status: 'Offline', avatar: null},
    { id: 11, name: 'Uchiha Sasuke', phoneNumber: '+2347058789012', status: 'Offline', avatar: null },
];

function sort(){
  let newList = contacts.sort((a,b) => a.name - a.name)
  return newList
}

export const callHistory = [
    { id: 1, name: 'John Doe', type: 'Video', date: '2025-03-28', duration: '5:32', status: 'Missed', phoneNumber: '+2347012345678', time: "8:30 pm" },
    { id: 2, name: 'Jane Smith', type: 'Audio', date: '2025-03-27', duration: '2:11', status: 'Missed', phoneNumber: '+2347023456789', time: "9:30 am" },
    { id: 3, name: 'Michael Johnson', type: 'Video', date: '2025-01-18', duration: '8:45', status: 'Completed', phoneNumber: '+2347034567890', time: "8:00 pm" },
    { id: 5, name: 'Chris Evans', type: 'Audio', date: '2025-01-15', duration: '0:45', status: 'Missed', phoneNumber: '+2347056789012', time: "3:30 am" },
    { id: 6, name: 'Chris Evans', type: 'Audio', date: '2025-01-28', duration: '0:45', status: 'Missed', phoneNumber: '+2347043952140', time: "12:00 pm" },
    { id: 4, name: 'Mary Johnson', type: 'Audio', date: '2024-01-17', duration: '3:05', status: 'Declined', phoneNumber: '+2347045678901', time: "10:30 pm" },
  ];

  export function formatDate(dates){
    const months = [
                    'Jan', 'Feb', 'Mar', 'Apr', 
                    'May', 'Jun', 'Jul', 'Aug', 
                    'Sept', 'Oct', 'Nov', 'Dec',
                   ]
    let year = Number(dates.split('-')[0]);
    const month = Number(dates.split('-')[1]);
    const date = Number(dates.split('-')[2]);
    const cYear = new Date().getFullYear();
    const cMonth = new Date().getMonth() + 1;
    const cDate = new Date().getDate();

    if(cYear !== year){ 
      year = year.toString()
      return `${month}/${date}/${year.split('')[2]}${year.split('')[3]}`
     }

    if(cMonth === month){
        let yesterday = cDate - 1;
        if(date === yesterday || yesterday === 0 && date === 1){ return 'Yesterday' };
        if(date === cDate){ return 'Today' };
    }
    
    return `${months[month - 1]} ${date}`
}

import profilePic from "../assets/images/profile.webp"
  
export const userProfile = {
    name: 'Nnamdi Amaga',
    phoneNumber: '+2347043952140',
    status: 'Online',
    profilePicture: profilePic, // URL to a random profile picture
    bio: 'Just a regular guy trying to connect with people.',
    lastActive: '2025-01-20 14:30',
};

export const incomingCall = {
    id: 1,
    name: 'Jane Smith',
    type: 'Video', // or 'Audio'
    status: 'Ringing', // Other possible status: 'Declined', 'Missed', 'Answered'
    callDuration: '0:00',
  };



  
export const settingsOptions = [
    { id: 1, name: 'Notifications', status: 'Enabled' },
    { id: 2, name: 'Privacy', status: 'Public' },
    { id: 3, name: 'Blocked Users', status: 'None' },
    { id: 4, name: 'Language', status: 'English' },
    { id: 5, name: 'Call Settings', status: 'Default' },
  ];


export const callFilters = ['All', 'Video', 'Audio', 'Missed', 'Completed'];

export function getFirstLetter(name){
  return name.toUpperCase()[0]
 }

export const countryPhoneCodes = [
  { country: "Afghanistan", code: "+93", flag: "af.png" },
  { country: "Albania", code: "+355", flag: "al.png" },
  { country: "Algeria", code: "+213", flag: "dz.png" },
  { country: "Andorra", code: "+376", flag: "ad.png" },
  { country: "Angola", code: "+244", flag: "ao.png" },
  { country: "Antigua and Barbuda", code: "+1-268", flag: "ag.png" },
  { country: "Argentina", code: "+54", flag: "ar.png" },
  { country: "Armenia", code: "+374", flag: "am.png" },
  { country: "Australia", code: "+61", flag: "au.png" },
  { country: "Austria", code: "+43", flag: "at.png" },
  { country: "Azerbaijan", code: "+994", flag: "az.png" },
  { country: "Bahamas", code: "+1-242", flag: "bs.png" },
  { country: "Bahrain", code: "+973", flag: "bh.png" },
  { country: "Bangladesh", code: "+880", flag: "bd.png" },
  { country: "Barbados", code: "+1-246", flag: "bb.png" },
  { country: "Belarus", code: "+375", flag: "by.png" },
  { country: "Belgium", code: "+32", flag: "be.png" },
  { country: "Belize", code: "+501", flag: "bz.png" },
  { country: "Benin", code: "+229", flag: "bj.png" },
  { country: "Bhutan", code: "+975", flag: "bt.png" },
  { country: "Bolivia", code: "+591", flag: "bo.png" },
  { country: "Bosnia and Herzegovina", code: "+387", flag: "ba.png" },
  { country: "Botswana", code: "+267", flag: "bw.png" },
  { country: "Brazil", code: "+55", flag: "br.png" },
  { country: "Brunei", code: "+673", flag: "bn.png" },
  { country: "Bulgaria", code: "+359", flag: "bg.png" },
  { country: "Burkina Faso", code: "+226", flag: "bf.png" },
  { country: "Burundi", code: "+257", flag: "bi.png" },
  { country: "Cabo Verde", code: "+238", flag: "cv.png" },
  { country: "Cambodia", code: "+855", flag: "kh.png" },
  { country: "Cameroon", code: "+237", flag: "cm.png" },
  { country: "Canada", code: "+1", flag: "ca.png" },
  { country: "Central African Republic", code: "+236", flag: "cf.png" },
  { country: "Chad", code: "+235", flag: "td.png" },
  { country: "Chile", code: "+56", flag: "cl.png" },
  { country: "China", code: "+86", flag: "cn.png" },
  { country: "Colombia", code: "+57", flag: "co.png" },
  { country: "Comoros", code: "+269", flag: "km.png" },
  { country: "Congo (Brazzaville)", code: "+242", flag: "cg.png" },
  { country: "Congo (Kinshasa)", code: "+243", flag: "cd.png" },
  { country: "Costa Rica", code: "+506", flag: "cr.png" },
  { country: "Croatia", code: "+385", flag: "hr.png" },
  { country: "Cuba", code: "+53", flag: "cu.png" },
  { country: "Cyprus", code: "+357", flag: "cy.png" },
  { country: "Czech Republic", code: "+420", flag: "cz.png" },
  { country: "Denmark", code: "+45", flag: "dk.png" },
  { country: "Djibouti", code: "+253", flag: "dj.png" },
  { country: "Dominica", code: "+1-767", flag: "dm.png" },
  { country: "Dominican Republic", code: "+1-809", flag: "do.png" },
  { country: "Ecuador", code: "+593", flag: "ec.png" },
  { country: "Egypt", code: "+20", flag: "eg.png" },
  { country: "El Salvador", code: "+503", flag: "sv.png" },
  { country: "Equatorial Guinea", code: "+240", flag: "gq.png" },
  { country: "Eritrea", code: "+291", flag: "er.png" },
  { country: "Estonia", code: "+372", flag: "ee.png" },
  { country: "Ethiopia", code: "+251", flag: "et.png" },
  { country: "Fiji", code: "+679", flag: "fj.png" },
  { country: "Finland", code: "+358", flag: "fi.png" },
  { country: "France", code: "+33", flag: "fr.png" },
  { country: "Gabon", code: "+241", flag: "ga.png" },
  { country: "Gambia", code: "+220", flag: "gm.png" },
  { country: "Georgia", code: "+995", flag: "ge.png" },
  { country: "Germany", code: "+49", flag: "de.png" },
  { country: "Ghana", code: "+233", flag: "gh.png" },
  { country: "Greece", code: "+30", flag: "gr.png" },
  { country: "Grenada", code: "+1-473", flag: "gd.png" },
  { country: "Guatemala", code: "+502", flag: "gt.png" },
  { country: "Guinea", code: "+224", flag: "gn.png" },
  { country: "Guinea-Bissau", code: "+245", flag: "gw.png" },
  { country: "Guyana", code: "+592", flag: "gy.png" },
  { country: "Haiti", code: "+509", flag: "ht.png" },
  { country: "Honduras", code: "+504", flag: "hn.png" },
  { country: "Hungary", code: "+36", flag: "hu.png" },
  { country: "Iceland", code: "+354", flag: "is.png" },
  { country: "India", code: "+91", flag: "in.png" },
  { country: "Indonesia", code: "+62", flag: "id.png" },
  { country: "Iran", code: "+98", flag: "ir.png" },
  { country: "Iraq", code: "+964", flag: "iq.png" },
  { country: "Ireland", code: "+353", flag: "ie.png" },
  { country: "Israel", code: "+972", flag: "il.png" },
  { country: "Italy", code: "+39", flag: "it.png" },
  { country: "Jamaica", code: "+1-876", flag: "jm.png" },
  { country: "Japan", code: "+81", flag: "jp.png" },
  { country: "Jordan", code: "+962", flag: "jo.png" },
  { country: "Kazakhstan", code: "+7", flag: "kz.png" },
  { country: "Kenya", code: "+254", flag: "ke.png" },
  { country: "Kiribati", code: "+686", flag: "ki.png" },
  { country: "Korea (North)", code: "+850", flag: "kp.png" },
  { country: "Korea (South)", code: "+82", flag: "kr.png" },
  { country: "Kuwait", code: "+965", flag: "kw.png" },
  { country: "Kyrgyzstan", code: "+996", flag: "kg.png" },
  { country: "Laos", code: "+856", flag: "la.png" },
  { country: "Latvia", code: "+371", flag: "lv.png" },
  { country: "Lebanon", code: "+961", flag: "lb.png" },
  { country: "Lesotho", code: "+266", flag: "ls.png" },
  { country: "Liberia", code: "+231", flag: "lr.png" },
  { country: "Libya", code: "+218", flag: "ly.png" },
  { country: "Liechtenstein", code: "+423", flag: "li.png" },
  { country: "Lithuania", code: "+370", flag: "lt.png" },
  { country: "Luxembourg", code: "+352", flag: "lu.png" },
  { country: "Madagascar", code: "+261", flag: "mg.png" },
  { country: "Malawi", code: "+265", flag: "mw.png" },
  { country: "Malaysia", code: "+60", flag: "my.png" },
  { country: "Maldives", code: "+960", flag: "mv.png" },
  { country: "Mali", code: "+223", flag: "ml.png" },
  { country: "Malta", code: "+356", flag: "mt.png" },
  { country: "Marshall Islands", code: "+692", flag: "mh.png" },
  { country: "Mauritania", code: "+222", flag: "mr.png" },
  { country: "Mauritius", code: "+230", flag: "mu.png" },
  { country: "Mexico", code: "+52", flag: "mx.png" },
  { country: "Micronesia", code: "+691", flag: "fm.png" },
  { country: "Moldova", code: "+373", flag: "md.png" },
  { country: "Monaco", code: "+377", flag: "mc.png" },
  { country: "Mongolia", code: "+976", flag: "mn.png" },
  { country: "Montenegro", code: "+382", flag: "me.png" },
  { country: "Morocco", code: "+212", flag: "ma.png" },
  { country: "Mozambique", code: "+258", flag: "mz.png" },
  { country: "Myanmar", code: "+95", flag: "mm.png" },
  { country: "Namibia", code: "+264", flag: "na.png" },
  { country: "Nauru", code: "+674", flag: "nr.png" },
  { country: "Nepal", code: "+977", flag: "np.png" },
  { country: "Netherlands", code: "+31", flag: "nl.png" },
  { country: "New Zealand", code: "+64", flag: "nz.png" },
  { country: "Nicaragua", code: "+505", flag: "ni.png" },
  { country: "Niger", code: "+227", flag: "ne.png" },
  { country: "Nigeria", code: "+234", flag: "ng.png" },
  { country: "North Macedonia", code: "+389", flag: "mk.png" },
  { country: "Norway", code: "+47", flag: "no.png" },
  { country: "Oman", code: "+968", flag: "om.png" },
  { country: "Pakistan", code: "+92", flag: "pk.png" },
  { country: "Palau", code: "+680", flag: "pw.png" },
  { country: "Panama", code: "+507", flag: "pa.png" },
  { country: "Papua New Guinea", code: "+675", flag: "pg.png" },
  { country: "Paraguay", code: "+595", flag: "py.png" },
  { country: "Peru", code: "+51", flag: "pe.png" },
  { country: "Philippines", code: "+63", flag: "ph.png" },
  { country: "Poland", code: "+48", flag: "pl.png" },
  { country: "Portugal", code: "+351", flag: "pt.png" },
  { country: "Qatar", code: "+974", flag: "qa.png" },
  { country: "Romania", code: "+40", flag: "ro.png" },
  { country: "Russia", code: "+7", flag: "ru.png" },
  { country: "Rwanda", code: "+250", flag: "rw.png" },
  { country: "Saint Kitts and Nevis", code: "+1-869", flag: "kn.png" },
  { country: "Saint Lucia", code: "+1-758", flag: "lc.png" },
  { country: "Saint Vincent and the Grenadines", code: "+1-784", flag: "vc.png" },
  { country: "Samoa", code: "+685", flag: "ws.png" },
  { country: "San Marino", code: "+378", flag: "sm.png" },
  { country: "Sao Tome and Principe", code: "+239", flag: "st.png" },
  { country: "Saudi Arabia", code: "+966", flag: "sa.png" },
  { country: "Senegal", code: "+221", flag: "sn.png" },
  { country: "Serbia", code: "+381", flag: "rs.png" },
  { country: "Seychelles", code: "+248", flag: "sc.png" },
  { country: "Sierra Leone", code: "+232", flag: "sl.png" },
  { country: "Singapore", code: "+65", flag: "sg.png" },
  { country: "Slovakia", code: "+421", flag: "sk.png" },
  { country: "Slovenia", code: "+386", flag: "si.png" },
  { country: "Solomon Islands", code: "+677", flag: "sb.png" },
  { country: "Somalia", code: "+252", flag: "so.png" },
  { country: "South Africa", code: "+27", flag: "za.png" },
  { country: "South Sudan", code: "+211", flag: "ss.png" },
  { country: "Spain", code: "+34", flag: "es.png" },
  { country: "Sri Lanka", code: "+94", flag: "lk.png" },
  { country: "Sudan", code: "+249", flag: "sd.png" },
  { country: "Suriname", code: "+597", flag: "sr.png" },
  { country: "Swaziland (Eswatini)", code: "+268", flag: "sz.png" },
  { country: "Sweden", code: "+46", flag: "se.png" },
  { country: "Switzerland", code: "+41", flag: "ch.png" },
  { country: "Syria", code: "+963", flag: "sy.png" },
  { country: "Taiwan", code: "+886", flag: "tw.png" },
  { country: "Tajikistan", code: "+992", flag: "tj.png" },
  { country: "Tanzania", code: "+255", flag: "tz.png" },
  { country: "Thailand", code: "+66", flag: "th.png" },
  { country: "Timor-Leste", code: "+670", flag: "tl.png" },
  { country: "Togo", code: "+228", flag: "tg.png" },
  { country: "Tonga", code: "+676", flag: "to.png" },
  { country: "Tunisia", code: "+216", flag: "tn.png" },
  { country: "Turkey", code: "+90", flag: "tr.png" },
  { country: "Turkmenistan", code: "+993", flag: "tm.png" },
  { country: "Tuvalu", code: "+688", flag: "tv.png" },
  { country: "Uganda", code: "+256", flag: "ug.png" },
  { country: "Ukraine", code: "+380", flag: "ua.png" },
  { country: "United Arab Emirates", code: "+971", flag: "ae.png" },
  { country: "United Kingdom", code: "+44", flag: "gb.png" },
  { country: "United States", code: "+1", flag: "us.png" },
  { country: "Uruguay", code: "+598", flag: "uy.png" },
  { country: "Uzbekistan", code: "+998", flag: "uz.png" },
  { country: "Vanuatu", code: "+678", flag: "vu.png" },
  { country: "Vatican City", code: "+379", flag: "va.png" },
  { country: "Venezuela", code: "+58", flag: "ve.png" },
  { country: "Vietnam", code: "+84", flag: "vn.png" },
  { country: "Yemen", code: "+967", flag: "ye.png" },
  { country: "Zambia", code: "+260", flag: "zm.png" },
  { country: "Zimbabwe", code: "+263", flag: "zw.png" },
];

// export const countryPhoneCodez = [
//   { country: "Afghanistan", code: "+93", flag: "af.png", regex: /^(\+93|0)?(2{1}[0-8]{1}|[3-5]{1}[0-4]{1})(\d{7})$/, min: "", max: "" },
//   { country: "Albania", code: "+355", flag: "al.png", regex: /^\+355[2-9]\d{7,8}$/, min: "", max: "" },
//   { country: "Algeria", code: "+213", flag: "dz.png", regex: /^(\+?213|0)(5|6|7)\d{8}$/, min: "", max: "" },
//   { country: "Andorra", code: "+376", flag: "ad.png", regex: /^(\+376)?[346]\d{5}$/, min: "", max: "" },
//   { country: "Angola", code: "+244", flag: "ao.png", regex: /^(\+244)\d{9}$/, min: "", max: "" },
//   { country: "Antigua and Barbuda", code: "+1-268", flag: "ag.png", regex: /^(?:\+1|1)268(?:464|7(?:1[3-9]|[28]\d|3[0246]|64|7[0-689]))\d{4}$/ },
//   { country: "Argentina", code: "+54", flag: "ar.png" , regex: /^\+?549(11|[2368]\d)\d{8}$/},
//   { country: "Armenia", code: "+374", flag: "am.png", regex: /^(\+?374|0)(33|4[134]|55|77|88|9[13-689])\d{6}$/ },
//   { country: "Australia", code: "+61", flag: "au.png", regex: /^(\+?61|0)4\d{8}$/ },
//   { country: "Austria", code: "+43", flag: "at.png", regex: /^\+43[1-9][0-9]{3,12}$/},
//   { country: "Azerbaijan", code: "+994", flag: "az.png", regex: /^(\+994|0)(10|5[015]|7[07]|99)\d{7}$/ },
//   { country: "Bahamas", code: "+1-242", flag: "bs.png", regex: /^(\+?1[-\s]?|0)?\(?242\)?[-\s]?\d{3}[-\s]?\d{4}$/},
//   { country: "Bahrain", code: "+973", flag: "bh.png", regex:/^(\+?973)?(3|6)\d{7}$/ },
//   { country: "Bangladesh", code: "+880", flag: "bd.png", regex: /^(\+?880|0)1[13456789][0-9]{8}$/ },
//   { country: "Barbados", code: "+1-246", flag: "bb.png", regex },
//   { country: "Belarus", code: "+375", flag: "by.png", regex: /^(\+?375)?(24|25|29|33|44)\d{7}$/ },
//   { country: "Belgium", code: "+32", flag: "be.png", regex: /^(\+?32|0)4\d{8}$/ },
//   { country: "Belize", code: "+501", flag: "bz.png", regex },
//   { country: "Benin", code: "+229", flag: "bj.png", regex: /^(\+229)\d{8}$/ },
//   { country: "Bhutan", code: "+975", flag: "bt.png", regex: /^(\+?975|0)?(17|16|77|02)\d{6}$/ },
//   { country: "Bolivia", code: "+591", flag: "bo.png", regex: /^(\+?591)?(6|7)\d{7}$/ },
//   { country: "Bosnia and Herzegovina", code: "+387", flag: "ba.png", regex: /^((((\+|00)3876)|06))((([0-3]|[5-6])\d{6})|(4\d{7}))$/ },
//   { country: "Botswana", code: "+267", flag: "bw.png", regex: /^(\+?267)?(7[1-8]{1})\d{6}$/ },
//   { country: "Brazil", code: "+55", flag: "br.png", regex: /^((\+?55\ ?[1-9]{2}\ ?)|(\+?55\ ?\([1-9]{2}\)\ ?)|(0[1-9]{2}\ ?)|(\([1-9]{2}\)\ ?)|([1-9]{2}\ ?))((\d{4}\-?\d{4})|(9[1-9]{1}\d{3}\-?\d{4}))$/ },
//   { country: "Brunei", code: "+673", flag: "bn.png" },
//   { country: "Bulgaria", code: "+359", flag: "bg.png", regex: /^(\+?359|0)?8[789]\d{7}$/ },
//   { country: "Burkina Faso", code: "+226", flag: "bf.png", regex: /^(\+226|0)[67]\d{7}$/ },
//   { country: "Burundi", code: "+257", flag: "bi.png" },
//   { country: "Cabo Verde", code: "+238", flag: "cv.png" },
//   { country: "Cambodia", code: "+855", flag: "kh.png" },
//   { country: "Cameroon", code: "+237", flag: "cm.png", regex: /^(\+?237)6[0-9]{8}$/ },
//   { country: "Canada", code: "+1", flag: "ca.png", regex: /^((\+1|1)?( |-)?)?(\([2-9][0-9]{2}\)|[2-9][0-9]{2})( |-)?([2-9][0-9]{2}( |-)?[0-9]{4})$/ },
//   { country: "Central African Republic", code: "+236", flag: "cf.png", regex: /^(\+?236| ?)(70|75|77|72|21|22)\d{6}$/ },
//   { country: "Chad", code: "+235", flag: "td.png" },
//   { country: "Chile", code: "+56", flag: "cl.png", regex: /^(\+?56|0)[2-9]\d{1}\d{7}$/ },
//   { country: "China", code: "+86", flag: "cn.png", regex: /^((\+|00)86)?(1[3-9]|9[28])\d{9}$/ },
//   { country: "Colombia", code: "+57", flag: "co.png", regex: /^(\+?57)?3(0(0|1|2|4|5)|1\d|2[0-4]|5(0|1))\d{7}$/ },
//   { country: "Comoros", code: "+269", flag: "km.png" },
//   { country: "Congo (Brazzaville)", code: "+242", flag: "cg.png", regex: /^(\+?242|0)?(8|9)\d{8}$/ },
//   { country: "Congo (Kinshasa)", code: "+243", flag: "cd.png", regex: /^(\+?243|0)?(8|9)\d{8}$/  },
//   { country: "Costa Rica", code: "+506", flag: "cr.png", regex: /^(\+506)?[2-8]\d{7}$/ },
//   { country: "Croatia", code: "+385", flag: "hr.png", regex: /^\+385[1-9][0-9]{7,8}$/ },
//   { country: "Cuba", code: "+53", flag: "cu.png", regex: /^(\+53|0053)?5\d{7}$/ },
//   { country: "Cyprus", code: "+357", flag: "cy.png", regex: /^(\+?357?)?(9(9|6)\d{6})$/ },
//   { country: "Czech Republic", code: "+420", flag: "cz.png", regex: /^(\+?420)? ?[1-9][0-9]{2} ?[0-9]{3} ?[0-9]{3}$/ },
//   { country: "Denmark", code: "+45", flag: "dk.png", regex: /^(\+?45)?\s?\d{2}\s?\d{2}\s?\d{2}\s?\d{2}$/ },
//   { country: "Djibouti", code: "+253", flag: "dj.png" },
//   // check dominica code
//   { country: "Dominica", code: "+1-767", flag: "dm.png", regex },
//   { country: "Dominican Republic", code: "+1-809", flag: "do.png", regex: /^(\+?1)?8[024]9\d{7}$/ },
//   { country: "Ecuador", code: "+593", flag: "ec.png", regex: /^(\+?593|0)([2-7]|9[2-9])\d{7}$/ },
//   { country: "Egypt", code: "+20", flag: "eg.png", regex: /^((\+?20)|0)?1[0125]\d{8}$/ },
//   { country: "El Salvador", code: "+503", flag: "sv.png", regex: /^(\+?503)?[67]\d{7}$/ },
//   { country: "Equatorial Guinea", code: "+240", flag: "gq.png" },
//   { country: "Eritrea", code: "+291", flag: "er.png" },
//   { country: "Estonia", code: "+372", flag: "ee.png", regex: /^(\+?372)?\s?(5|8[1-4])\s?([0-9]\s?){6,7}$/ },
//   { country: "Ethiopia", code: "+251", flag: "et.png" },
//   { country: "Fiji", code: "+679", flag: "fj.png", regex: /^(\+?679)?\s?\d{3}\s?\d{4}$/ },
//   { country: "Finland", code: "+358", flag: "fi.png", regex: /^(\+?358|0)\s?(4[0-6]|50)\s?(\d\s?){4,8}$/ },
//   { country: "France", code: "+33", flag: "fr.png", regex: /^(\+?33|0)[67]\d{8}$/ },
//   { country: "Gabon", code: "+241", flag: "ga.png" },
//   { country: "Gambia", code: "+220", flag: "gm.png" },
//   { country: "Georgia", code: "+995", flag: "ge.png" , regex: /^(\+?995)?(79\d{7}|5\d{8})$/},
//   { country: "Germany", code: "+49", flag: "de.png", regex: /^((\+49|0)1)(5[0-25-9]\d|6([23]|0\d?)|7([0-57-9]|6\d))\d{7,9}$/ },
//   { country: "Ghana", code: "+233", flag: "gh.png", regex: /^(\+233|0)(20|50|24|54|27|57|26|56|23|28|55|59)\d{7}$/ },
//   { country: "Greece", code: "+30", flag: "gr.png", regex: /^(\+?30|0)?6(8[5-9]|9(?![26])[0-9])\d{7}$/ },
//   // Greenland
//   // Guadeloupe
//   // Guernsey
//   // Guyana
//   { country: "Grenada", code: "+1-473", flag: "gd.png" },
//   { country: "Guatemala", code: "+502", flag: "gt.png" },
//   { country: "Guinea", code: "+224", flag: "gn.png" },
//   { country: "Guinea-Bissau", code: "+245", flag: "gw.png" },
//   { country: "Guyana", code: "+592", flag: "gy.png" },
//   { country: "Haiti", code: "+509", flag: "ht.png" },
//   { country: "Honduras", code: "+504", flag: "hn.png", regex: /^(\+?504)?[9|8|3|2]\d{7}$/ },
//   { country: "Hong Kong", code: "+852", flag: "hk.png", regex: /^(\+?852[-\s]?)?[456789]\d{3}[-\s]?\d{4}$/ },
//   { country: "Hungary", code: "+36", flag: "hu.png", regex: /^(\+?36|06)(20|30|31|50|70)\d{7}$/},
//   { country: "Iceland", code: "+354", flag: "is.png", regex: /^\+354[0-9]{7}$/ },
//   { country: "India", code: "+91", flag: "in.png", regex: /^(\+?91|0)?[6789]\d{9}$/ },
//   { country: "Indonesia", code: "+62", flag: "id.png", regex: /^(\+?62|0)8(1[123456789]|2[1238]|3[1238]|5[12356789]|7[78]|9[56789]|8[123456789])([\s?|\d]{5,11})$/ },
//   { country: "Iran", code: "+98", flag: "ir.png", regex: /^(\+98|0)?9\d{9}/ },
//   { country: "Iraq", code: "+964", flag: "iq.png", regex: /^(\+?964|0)?7[0-9]\d{8}$/ },
//   { country: "Ireland", code: "+353", flag: "ie.png", regex: /^(\+?353|0)8[356789]\d{7}$/ },
//   { country: "Israel", code: "+972", flag: "il.png", regex },
//   { country: "Italy", code: "+39", flag: "it.png", regex: /^(\+?39)?\s?3\d{2} ?\d{6,7}$/ },
//   { country: "Jamaica", code: "+1-876", flag: "jm.png", regex: /^(\+?876)?\d{7}$/ }, //check this countries code
//   { country: "Japan", code: "+81", flag: "jp.png", regex: /^(\+81[ \-]?(\(0\))?|0)[6789]0[ \-]?\d{4}[ \-]?\d{4}$/ },
//   { country: "Jordan", code: "+962", flag: "jo.png", regex: /^(\+?962|0)?7[789]\d{7}$/ },
//   { country: "Kazakhstan", code: "+7", flag: "kz.png", regex: /^(\+?7|8)?7\d{9}$/ },
//   { country: "Kenya", code: "+254", flag: "ke.png", regex: /^(\+?254|0)(7|1)\d{8}$/ },
//   { country: "Kiribati", code: "+686", flag: "ki.png", regex: /^((\+686|686)?)?( )?((6|7)(2|3|8)[0-9]{6})$/ },
//   { country: "Korea (North)", code: "+850", flag: "kp.png" },
//   { country: "Korea (South)", code: "+82", flag: "kr.png", regex: /^((\+?82)[ \-]?)?0?1([0|1|6|7|8|9]{1})[ \-]?\d{3,4}[ \-]?\d{4}$/ },
//   { country: "Kosovo", code: "+383", flag: "kw.png", regex: /^\+383[1-9][0-9]{6,7}$/ },
//   { country: "Kuwait", code: "+965", flag: "kw.png", regex: /^(\+?965)([569]\d{7}|41\d{6})$/ },
//   { country: "Kyrgyzstan", code: "+996", flag: "kg.png", regex: /^(\+?7\s?\+?7|0)\s?\d{2}\s?\d{3}\s?\d{4}$/ },//the regex might be wrong
//   { country: "Laos", code: "+856", flag: "la.png" },
//   { country: "Latvia", code: "+371", flag: "lv.png" },
//   { country: "Lebanon", code: "+961", flag: "lb.png" },
//   { country: "Lesotho", code: "+266", flag: "ls.png" },
//   { country: "Liberia", code: "+231", flag: "lr.png" },
//   { country: "Libya", code: "+218", flag: "ly.png" },
//   { country: "Liechtenstein", code: "+423", flag: "li.png" },
//   { country: "Lithuania", code: "+370", flag: "lt.png" },
//   { country: "Luxembourg", code: "+352", flag: "lu.png" },
//   { country: "Madagascar", code: "+261", flag: "mg.png" },
//   { country: "Malawi", code: "+265", flag: "mw.png" },
//   { country: "Malaysia", code: "+60", flag: "my.png" },
//   { country: "Maldives", code: "+960", flag: "mv.png" },
//   { country: "Mali", code: "+223", flag: "ml.png" },
//   { country: "Malta", code: "+356", flag: "mt.png" },
//   { country: "Marshall Islands", code: "+692", flag: "mh.png" },
//   { country: "Mauritania", code: "+222", flag: "mr.png" },
//   { country: "Mauritius", code: "+230", flag: "mu.png" },
//   { country: "Mexico", code: "+52", flag: "mx.png" },
//   { country: "Micronesia", code: "+691", flag: "fm.png" },
//   { country: "Moldova", code: "+373", flag: "md.png" },
//   { country: "Monaco", code: "+377", flag: "mc.png" },
//   { country: "Mongolia", code: "+976", flag: "mn.png" },
//   { country: "Montenegro", code: "+382", flag: "me.png" },
//   { country: "Morocco", code: "+212", flag: "ma.png" },
//   { country: "Mozambique", code: "+258", flag: "mz.png" },
//   { country: "Myanmar", code: "+95", flag: "mm.png" },
//   { country: "Namibia", code: "+264", flag: "na.png" },
//   { country: "Nauru", code: "+674", flag: "nr.png" },
//   { country: "Nepal", code: "+977", flag: "np.png" },
//   { country: "Netherlands", code: "+31", flag: "nl.png" },
//   { country: "New Zealand", code: "+64", flag: "nz.png" },
//   { country: "Nicaragua", code: "+505", flag: "ni.png" },
//   { country: "Niger", code: "+227", flag: "ne.png" },
//   { country: "Nigeria", code: "+234", flag: "ng.png" },
//   { country: "North Macedonia", code: "+389", flag: "mk.png" },
//   { country: "Norway", code: "+47", flag: "no.png" },
//   { country: "Oman", code: "+968", flag: "om.png" },
//   { country: "Pakistan", code: "+92", flag: "pk.png" },
//   { country: "Palau", code: "+680", flag: "pw.png" },
//   { country: "Panama", code: "+507", flag: "pa.png" },
//   { country: "Papua New Guinea", code: "+675", flag: "pg.png" },
//   { country: "Paraguay", code: "+595", flag: "py.png" },
//   { country: "Peru", code: "+51", flag: "pe.png" },
//   { country: "Philippines", code: "+63", flag: "ph.png" },
//   { country: "Poland", code: "+48", flag: "pl.png" },
//   { country: "Portugal", code: "+351", flag: "pt.png" },
//   { country: "Qatar", code: "+974", flag: "qa.png" },
//   { country: "Romania", code: "+40", flag: "ro.png" },
//   { country: "Russia", code: "+7", flag: "ru.png" },
//   { country: "Rwanda", code: "+250", flag: "rw.png" },
//   { country: "Saint Kitts and Nevis", code: "+1-869", flag: "kn.png" },
//   { country: "Saint Lucia", code: "+1-758", flag: "lc.png" },
//   { country: "Saint Vincent and the Grenadines", code: "+1-784", flag: "vc.png" },
//   { country: "Samoa", code: "+685", flag: "ws.png" },
//   { country: "San Marino", code: "+378", flag: "sm.png" },
//   { country: "Sao Tome and Principe", code: "+239", flag: "st.png" },
//   { country: "Saudi Arabia", code: "+966", flag: "sa.png" },
//   { country: "Senegal", code: "+221", flag: "sn.png" },
//   { country: "Serbia", code: "+381", flag: "rs.png" },
//   { country: "Seychelles", code: "+248", flag: "sc.png" },
//   { country: "Sierra Leone", code: "+232", flag: "sl.png" },
//   { country: "Singapore", code: "+65", flag: "sg.png" },
//   { country: "Slovakia", code: "+421", flag: "sk.png" },
//   { country: "Slovenia", code: "+386", flag: "si.png" },
//   { country: "Solomon Islands", code: "+677", flag: "sb.png" },
//   { country: "Somalia", code: "+252", flag: "so.png" },
//   { country: "South Africa", code: "+27", flag: "za.png" },
//   { country: "South Sudan", code: "+211", flag: "ss.png" },
//   { country: "Spain", code: "+34", flag: "es.png" },
//   { country: "Sri Lanka", code: "+94", flag: "lk.png" },
//   { country: "Sudan", code: "+249", flag: "sd.png" },
//   { country: "Suriname", code: "+597", flag: "sr.png" },
//   { country: "Swaziland (Eswatini)", code: "+268", flag: "sz.png" },
//   { country: "Sweden", code: "+46", flag: "se.png" },
//   { country: "Switzerland", code: "+41", flag: "ch.png" },
//   { country: "Syria", code: "+963", flag: "sy.png" },
//   { country: "Taiwan", code: "+886", flag: "tw.png" },
//   { country: "Tajikistan", code: "+992", flag: "tj.png" },
//   { country: "Tanzania", code: "+255", flag: "tz.png" },
//   { country: "Thailand", code: "+66", flag: "th.png" },
//   { country: "Timor-Leste", code: "+670", flag: "tl.png" },
//   { country: "Togo", code: "+228", flag: "tg.png" },
//   { country: "Tonga", code: "+676", flag: "to.png" },
//   { country: "Tunisia", code: "+216", flag: "tn.png" },
//   { country: "Turkey", code: "+90", flag: "tr.png" },
//   { country: "Turkmenistan", code: "+993", flag: "tm.png" },
//   { country: "Tuvalu", code: "+688", flag: "tv.png" },
//   { country: "Uganda", code: "+256", flag: "ug.png" },
//   { country: "Ukraine", code: "+380", flag: "ua.png" },
//   { country: "United Arab Emirates", code: "+971", flag: "ae.png" },
//   { country: "United Kingdom", code: "+44", flag: "gb.png" },
//   { country: "United States", code: "+1", flag: "us.png" },
//   { country: "Uruguay", code: "+598", flag: "uy.png" },
//   { country: "Uzbekistan", code: "+998", flag: "uz.png" },
//   { country: "Vanuatu", code: "+678", flag: "vu.png" },
//   { country: "Vatican City", code: "+379", flag: "va.png" },
//   { country: "Venezuela", code: "+58", flag: "ve.png" },
//   { country: "Vietnam", code: "+84", flag: "vn.png" },
//   { country: "Yemen", code: "+967", flag: "ye.png" },
//   { country: "Zambia", code: "+260", flag: "zm.png" },
//   { country: "Zimbabwe", code: "+263", flag: "zw.png" },
// ];

